name: Data515-LIME
channels:
  - defaults
dependencies:
  - certifi=2019.3.9=py36_0
  - pip=19.1.1=py36_0
  - pip:
    - joblib==0.13.2
    - numpy==1.16.3
    - pandas==0.24.2
    - python-dateutil==2.8.0
    - python-graphviz==0.10.1
    - pytz==2019.1
    - scikit-learn==0.21.1
    - scipy==1.3.0
    - six==1.12.0
    - sklearn==0.0
