name: LIMEaid
channels:
  - defaults
dependencies:
  - certifi=2019.3.9=py36_0
  - pip=19.1.1=py36_0
  - pip:
    - joblib==0.13.2
    - numpy==1.16.3
    - pandas==0.24.2
    - python-dateutil==2.8.0
    - scikit-learn
    - matplotlib
    - graphviz
